rootProject.name = "CSGOCasesWatcherApp"


include ':app'
include ':core:ui'
include ':core:serialization'


include ':feature:start'
include ':domain:start'
include ':data:start'

include ':domain:portfolio'
include ':feature:portfolio'

include ':feature:caseoverview'
include ':domain:caseoverview'

include ':feature:caseanalytics'
include ':domain:caseanalytics'

include ':feature:addcase'
include ':domain:addcase'

include ':feature:currencychange'

include ':feature:caseoverviewdetails'

include ':feature:portfoliodetails'
include ':data:caseoverview'
include ':data:caseanalytics'
include ':data:portfolio'
include ':data:addcase'
include ':core:network'
include ':data:remote'
include ':data:local'
