rootProject.name = "CSGOCasesWatcherApp"


include ':app'
include ':core:ui'
include ':core:serialization'
include ':feature:currencychange'
include ':feature:start'
include ':domain:start'

include ':domain:caseoverview'
include ':feature:caseoverview'
include ':domain:caseanalytics'
include ':feature:caseanalytics'
