plugins {
    id 'com.android.library'
    
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'com.google.devtools.ksp'
    id 'com.google.dagger.hilt.android'
}

android {
    namespace = 'com.example.csgocaseswatcherapp.features.start.data'
    compileSdk = 37

    defaultConfig {
        minSdk = 26

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        freeCompilerArgs.add("-jvm-default=enable")
    }
}

dependencies {
    implementation project(':feature:start:domain')

    implementation 'androidx.core:core-ktx:1.16.0'

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"

    implementation "com.google.dagger:hilt-android:2.59.2"
    ksp "com.google.dagger:hilt-android-compiler:2.59.2"

    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}