plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
    id 'com.google.devtools.ksp'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'kotlin-parcelize'
    id 'com.google.dagger.hilt.android'
}
android {
    namespace 'com.example.csgocaseswatcherapp'
    compileSdkVersion 35
    flavorDimensions += "data"

    buildFeatures {
        buildConfig true
        compose true
        viewBinding = true
    }

    productFlavors {
        create("remote") { dimension = "data" }
        create("local") { dimension = "data" }
    }

    defaultConfig {
        applicationId "com.example.csgocaseswatcherapp"
        minSdkVersion 26
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
        freeCompilerArgs = ['-Xjvm-default=all']

    }
}

dependencies {

    remoteImplementation project(':data:remote')

    localImplementation project(':data:local')

    implementation project(':core:ui')
    implementation project(':core:serialization')
    implementation project(':core:network')

    implementation project(':feature:start')
    implementation project(':domain:start')
    implementation project(':data:start')

    implementation project(':feature:caseoverview')
    implementation project(':domain:caseoverview')
    implementation project(':data:caseoverview')

    implementation project(':feature:caseanalytics')
    implementation project(':domain:caseanalytics')
    implementation project(':data:caseanalytics')

    implementation project(':feature:portfolio')
    implementation project(':domain:portfolio')
    implementation project(':data:portfolio')

    implementation project(':feature:addcase')
    implementation project(':domain:addcase')
    implementation project(':data:addcase')

    implementation project(':feature:currencychange')
    implementation project(':feature:portfoliodetails')
    implementation project(':feature:caseoverviewdetails')

    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'

    implementation platform('androidx.compose:compose-bom:2025.07.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.compose.material3:material3-android:1.3.2'
    debugImplementation 'androidx.compose.ui:ui-tooling'

    implementation "androidx.navigation:navigation-compose:2.9.4"

    implementation "androidx.room:room-runtime:2.7.2"
    implementation "androidx.room:room-ktx:2.7.2"
    ksp "androidx.room:room-compiler:2.7.2"

    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.9.2"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.2"

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0"

    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"
    implementation "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0"

    implementation "com.google.dagger:hilt-android:2.52"
    kapt "com.google.dagger:hilt-android-compiler:2.52"
    implementation "androidx.hilt:hilt-navigation-compose:1.2.0"

    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'


    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    implementation "io.coil-kt:coil-compose:2.7.0"

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0'
    testImplementation 'app.cash.turbine:turbine:1.1.0'
    testImplementation 'com.willowtreeapps.assertk:assertk-jvm:0.28.1'
    testImplementation 'io.mockk:mockk:1.13.13'
    testImplementation 'org.threeten:threetenbp:1.6.8'

    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0'
    androidTestImplementation 'app.cash.turbine:turbine:1.1.0'
    androidTestImplementation 'io.mockk:mockk-android:1.13.13'
    androidTestImplementation 'com.willowtreeapps.assertk:assertk-jvm:0.28.1'
}




