plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

android {
    namespace 'com.example.csgocaseswatcherapp.api'
    compileSdk 35

    defaultConfig {
        minSdk 26

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
        freeCompilerArgs = ['-Xjvm-default=all']
    }
}

dependencies {
    implementation project(':data:start')
    implementation project(':data:caseoverview')
    implementation project(':data:caseanalytics')
    implementation project(':data:portfolio')
    implementation project(':feature:addcase:data')

    implementation 'androidx.core:core-ktx:1.16.0'

    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"

    implementation 'com.squareup.retrofit2:retrofit:2.11.0'

    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}